version: 2.1

orbs:
  android: circleci/android@1.0

jobs:
  build:
    executor: android/android

    steps:
      - checkout

      - run:
          name: chmod permissions
          command: chmod +x ./gradlew

      - run:
          name: Check code and run tests
          command: |
            ./gradlew checkCode
